
main-site:
    server-name: mysite.us/
    image: mysite-static:latest

flask-server:
    server-name: mysite.us/flask
    image: myflask:latest

your-site:
    server-name: yoursite.com
    image: yourstatic:latest
